# Generated by Django 4.2 on 2025-05-17 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('objective', models.CharField(max_length=255)),
                ('factor', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('expect', models.CharField(max_length=100)),
                ('avenue', models.CharField(max_length=255)),
                ('advice_html', models.TextField()),
                ('similar_profiles_json', models.JSONField()),
                ('similar_profiles_percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
