# Generated by Django 4.2 on 2025-05-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_advicehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advicehistory',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
