# Generated by Django 4.2 on 2025-05-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_alter_advicehistory_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advicehistory',
            name='similar_profiles_json',
        ),
    ]
